# Generated by Django 5.1.4 on 2025-01-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_ascii', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('geoname_id', models.PositiveIntegerField()),
                ('alternate_names', models.TextField(blank=True, null=True)),
                ('code2', models.CharField(max_length=10)),
                ('code3', models.CharField(max_length=10)),
                ('continent', models.CharField(max_length=50)),
                ('tld', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.AddField(
            model_name='registroplanta',
            name='imagen_registro_planta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_registro_plantas/'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_ascii', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('geoname_id', models.PositiveIntegerField()),
                ('alternate_names', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.PositiveIntegerField()),
                ('featured_code', models.CharField(blank=True, max_length=20, null=True)),
                ('search_names', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_editado', models.DateTimeField(auto_now=True)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.city')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_ascii', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('geoname_id', models.PositiveIntegerField()),
                ('alternate_names', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('geoname_code', models.CharField(max_length=20)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.country')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.region'),
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id_sub_region', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_ascii', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('geoname_id', models.PositiveIntegerField()),
                ('alternate_names', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('geoname_code', models.CharField(max_length=20)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.country')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.region')),
            ],
            options={
                'db_table': 'sub_region',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='id_sub_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.subregion'),
        ),
    ]
