# Generated by Django 5.1.4 on 2025-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='codigoqr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='imagen_espacio',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_espacios/'),
        ),
    ]
