# Generated by Django 5.1.4 on 2025-02-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hume',
            new_name='TablaHumedal',
        ),
        migrations.RenameField(
            model_name='tablahumedal',
            old_name='id_hume',
            new_name='id_humedal',
        ),
        migrations.AlterModelTable(
            name='tablahumedal',
            table='tabla_humedal',
        ),
    ]
