# Generated by Django 5.1.4 on 2025-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_remove_sensor_descripcion_remove_sensor_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
