# Generated by Django 5.1.4 on 2025-01-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_alter_arduino_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='estado',
            field=models.IntegerField(),
        ),
    ]
