# Generated by Django 5.1.4 on 2025-01-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_rename_uuid_arduino_arduino_uuid_arduino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroplanta',
            old_name='observaciones_Registro',
            new_name='observaciones_registro',
        ),
    ]
