# Generated by Django 5.1.4 on 2025-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_modelosensor2_tipodato2_remove_arduino2_id_espacio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablahumedal',
            name='imagen_humedal',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_humedales/'),
        ),
    ]
