# Generated by Django 5.1.4 on 2025-01-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0004_parcela_planta_tipo_planta_division_parcela_arduino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduino',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='datos_sensores',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='datos_sensores',
            name='tipo_dato',
        ),
        migrations.RemoveField(
            model_name='division_parcela',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='registro_planta',
            name='division_parcela',
        ),
        migrations.DeleteModel(
            name='Modelo_sensor',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='tipo_planta',
        ),
        migrations.RemoveField(
            model_name='registro_planta',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='id',
        ),
        migrations.AddField(
            model_name='parcela',
            name='id_parcela',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcela',
            name='zona',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterModelTable(
            name='parcela',
            table='parcela',
        ),
        migrations.DeleteModel(
            name='Arduino',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Datos_sensores',
        ),
        migrations.DeleteModel(
            name='Tipo_dato',
        ),
        migrations.DeleteModel(
            name='Division_parcela',
        ),
        migrations.DeleteModel(
            name='Tipo_planta',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.DeleteModel(
            name='Registro_planta',
        ),
    ]
