# Generated by Django 5.1.4 on 2025-01-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0005_remove_arduino_parcela_remove_datos_sensores_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcela',
            old_name='id_parcela',
            new_name='id',
        ),
    ]
