# Generated by Django 5.1.4 on 2025-01-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0006_rename_id_parcela_parcela_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='id',
        ),
        migrations.AddField(
            model_name='parcela',
            name='id_parcela',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
