# Generated by Django 5.1.4 on 2025-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0007_remove_parcela_id_parcela_id_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='id_parcela',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
