# Generated by Django 5.1.4 on 2025-01-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0008_alter_parcela_id_parcela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcela',
        ),
    ]
