# Generated by Django 5.1.4 on 2025-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0011_modelosensor_planta_tipodato_tipoplanta_arduino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='UUID_parcela',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
