# Generated by Django 5.1.4 on 2025-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0012_alter_parcela_uuid_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='imagen_parcela',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_parcelas/'),
        ),
    ]
