# Generated by Django 5.1.4 on 2025-01-13 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0013_alter_parcela_imagen_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='UUID_parcela',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
