# Generated by Django 5.1.4 on 2025-01-15 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0014_alter_parcela_uuid_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='UUID_arduino',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='tipoplanta',
            name='UUID_tipo_planta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='tipoplanta',
            name='imagen_tipo_planta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_tipo_plantas/'),
        ),
        migrations.AlterField(
            model_name='registrosensor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
