# Generated by Django 5.1.4 on 2025-01-13 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0014_alter_parcela_uuid_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplanta',
            name='UUID_tipo_planta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
