# Generated by Django 5.1.4 on 2025-01-13 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0015_tipoplanta_uuid_tipo_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='UUID_arduino',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
