# Generated by Django 5.1.4 on 2025-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0016_arduino_uuid_arduino'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplanta',
            name='imagen_tipo_planta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_tipo_plantas/'),
        ),
    ]
