# Generated by Django 5.1.4 on 2025-01-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0017_tipoplanta_imagen_tipo_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosensor',
            name='fecha_registro',
            field=models.DateTimeField(),
        ),
    ]
